### ISSUE TITLE
Is this template still available?

### ISSUE THREAD

**Issue by MiraiHattori** [jsk-report-template/ieee-report#6]
Some people say the Humanoids rejected papers from this template.
I'm not sure how to fix this problem, but I'd like to warn this template might not follow the current [IEEEtrans.cls](https://www.ieee.org/conferences/publishing/templates.html)

**Comment by pazeshun** [comment]
@future731 Thank you for the report.

> Some people say the Humanoids rejected papers from this template.

Please tell me the rejected reason about the template.

**Comment by pazeshun** [comment]
I checked the PDF currently created by `make` with https://ras.papercept.net/conferences/scripts/pdftest.pl.
That PDF includes no error against Humanoids 2019 format.
I'll debug @takayuki5168's specific case.

**Comment by pazeshun** [comment]
> Please tell me the rejected reason about the template.

I and @future731 talked offline, and searched for rejected reasons.
Finally, we found that the latest version of this template was not used in the rejected cases.
> Some people say the Humanoids rejected papers from this template.

This seems wrong.

**Comment by pazeshun** [comment]
> I'd like to warn this template might not follow the current [IEEEtrans.cls](https://www.ieee.org/conferences/publishing/templates.html)

The template in the linked web site was surely updated in October 2019.
However, I found this is not the template specified from conference committees.
Now I think we don't have to change the template in this repo.

Conference "Call for papers" announcements ([Humanoids2019](http://humanoids2019.loria.fr/submissions/paper-submission/), [IROS2019](https://www.iros2019.org/contributing), [ICRA2020](https://www.icra2020.org/call-for-papers)) say the latex template is in PaperPlaza, not the above web site.
In PaperPlaza, the template `ieeeconf.zip` can be downloaded from http://ras.papercept.net/conferences/support/tex.php (some "Call for papers" announcements have direct link to that page).
This zip file includes `ieeeconf.cls` and its difference from `ieeeconf.cls` in this repo is small (and meaningless in our current usage):
```
$ diff -u ieeeconf.cls ~/Downloads/ieeeconf/ieeeconf.cls 
--- ieeeconf.cls	2019-10-21 20:03:41.363382464 +0900
+++ /home/pazeshun/Downloads/ieeeconf/ieeeconf.cls	2019-10-23 16:31:10.448556057 +0900
@@ -661,7 +661,7 @@
 %
 %
 %
-\ProvidesClass{cssconf}[2004/1/15 revision V1.6b by Pradeep Misra]
+\ProvidesClass{ieeeconf}[2016/4/23 revision V1.6b by Pradeep Misra]
 %\ProvidesClass{IEEEtran}[2002/11/18 revision V1.6b by Michael Shell]
 %\typeout{-- See the "IEEEtran_HOWTO" manual for usage information.}
 %\typeout{-- The source comments contain changelog notes.}
```

**Comment by pazeshun** [comment]
> This zip file includes `ieeeconf.cls` and its difference from `ieeeconf.cls` in this repo is small (and meaningless in our current usage):

I created #7 to import this small difference.

**Comment by pazeshun** [comment]
Closed because all problems seem solved.
